const phrases = [
    { english: "I love apples", french: "J'aime les pommes" },
    { english: "She is reading a book", french: "Elle lit un livre" },
    { english: "We are going to the park", french: "Nous allons au parc" },
    { english: "He is playing soccer", french: "Il joue au football" },
    { english: "They are watching a movie", french: "Ils regardent un film" },
    { english: "I am cooking dinner", french: "Je prépare le dîner" },
    { english: "You are very kind", french: "Tu es très gentil" },
    { english: "It is raining outside", french: "Il pleut dehors" },
    { english: "We are learning French", french: "Nous apprenons le français" },
    { english: "The cat is sleeping", french: "Le chat dort" },
    { english: "She likes to dance", french: "Elle aime danser" },
    { english: "He is a good student", french: "C'est un bon élève" },
    { english: "They are my friends", french: "Ce sont mes amis" },
    { english: "I have two brothers", french: "J'ai deux frères" },
    { english: "We live in Paris", french: "Nous habitons à Paris" },
    { english: "She is very intelligent", french: "Elle est très intelligente" },
    { english: "The dog is barking", french: "Le chien aboie" },
    { english: "He is wearing a hat", french: "Il porte un chapeau" },
    { english: "They are eating lunch", french: "Ils déjeunent" },
    { english: "I like to play guitar", french: "J'aime jouer de la guitare" },
    { english: "She is my sister", french: "Elle est ma sœur" },
    { english: "We are studying math", french: "Nous étudions les mathématiques" },
    { english: "He drives a car", french: "Il conduit une voiture" },
    { english: "They go to school", french: "Ils vont à l'école" },
    { english: "I have a new phone", french: "J'ai un nouveau téléphone" },
    { english: "She is singing a song", french: "Elle chante une chanson" },
    { english: "We like to swim", french: "Nous aimons nager" },
    { english: "He is very tall", french: "Il est très grand" },
    { english: "They live in a big house", french: "Ils vivent dans une grande maison" },
    { english: "I am a teacher", french: "Je suis professeur" },
    { english: "She is an artist", french: "Elle est artiste" },
    { english: "We have a dog", french: "Nous avons un chien" },
    { english: "He is very strong", french: "Il est très fort" },
    { english: "They are eating dinner", french: "Ils dînent" },
    { english: "I am writing a letter", french: "J'écris une lettre" },
    { english: "She is drinking water", french: "Elle boit de l'eau" },
    { english: "We are playing a game", french: "Nous jouons à un jeu" },
    { english: "He is fixing the car", french: "Il répare la voiture" },
    { english: "They are reading books", french: "Ils lisent des livres" },
    { english: "I like to travel", french: "J'aime voyager" },
    { english: "She is a nurse", french: "Elle est infirmière" },
    { english: "We are very happy", french: "Nous sommes très heureux" },
    { english: "He is a doctor", french: "Il est médecin" },
    { english: "They are watching TV", french: "Ils regardent la télévision" },
    { english: "I am going to the store", french: "Je vais au magasin" },
    { english: "She is painting a picture", french: "Elle peint un tableau" },
    { english: "We are having a party", french: "Nous faisons une fête" },
    { english: "He is reading a newspaper", french: "Il lit un journal" },
    { english: "They are playing tennis", french: "Ils jouent au tennis" },
    { english: "I like chocolate", french: "J'aime le chocolat" },
    { english: "She is a good cook", french: "Elle est une bonne cuisinière" },
    { english: "We are learning English", french: "Nous apprenons l'anglais" },
    { english: "He is very funny", french: "Il est très drôle" },
    { english: "They are going to the beach", french: "Ils vont à la plage" },
    { english: "I have a cat", french: "J'ai un chat" },
    { english: "She is playing the piano", french: "Elle joue du piano" },
    { english: "We are watching a play", french: "Nous regardons une pièce de théâtre" },
    { english: "He is making dinner", french: "Il prépare le dîner" },
    { english: "They are studying science", french: "Ils étudient les sciences" },
    { english: "I am reading a magazine", french: "Je lis un magazine" },
    { english: "She is writing a poem", french: "Elle écrit un poème" },
    { english: "We are going shopping", french: "Nous allons faire du shopping" },
    { english: "He is drawing a picture", french: "Il dessine un tableau" },
    { english: "They are listening to music", french: "Ils écoutent de la musique" },
    { english: "I like to read", french: "J'aime lire" },
    { english: "She is wearing a dress", french: "Elle porte une robe" },
    { english: "We are going to a concert", french: "Nous allons à un concert" },
    { english: "He is playing basketball", french: "Il joue au basket" },
    { english: "They are playing chess", french: "Ils jouent aux échecs" },
    { english: "I have a new car", french: "J'ai une nouvelle voiture" },
    { english: "She is baking a cake", french: "Elle fait un gâteau" },
    { english: "We are going for a walk", french: "Nous allons nous promener" },
    { english: "He is playing the violin", french: "Il joue du violon" },
    { english: "They are cleaning the house", french: "Ils nettoient la maison" },
    { english: "I like ice cream", french: "J'aime la glace" },
    { english: "She is a teacher", french: "Elle est enseignante" },
    { english: "We are watching the news", french: "Nous regardons les nouvelles" },
    { english: "He is very tired", french: "Il est très fatigué" },
    { english: "They are visiting a museum", french: "Ils visitent un musée" },
    { english: "I have a bike", french: "J'ai un vélo" },
    { english: "She is a student", french: "Elle est étudiante" },
    { english: "He is watching TV", french: "Il regarde la télévision" },
    { english: "We are running in the park", french: "Nous courons dans le parc" },
    { english: "She is drinking coffee", french: "Elle boit du café" },
    { english: "They are playing soccer", french: "Ils jouent au football" },
    { english: "I like to swim", french: "J'aime nager" },
    { english: "He is studying English", french: "Il étudie l'anglais" },
    { english: "She is cooking dinner", french: "Elle prépare le dîner" },
    { english: "We are listening to music", french: "Nous écoutons de la musique" },
    { english: "He is reading a book", french: "Il lit un livre" },
    { english: "They are eating lunch", french: "Ils déjeunent" },
    { english: "I am playing guitar", french: "Je joue de la guitare" },
    { english: "She is walking in the park", french: "Elle se promène dans le parc" },
    { english: "He is drinking water", french: "Il boit de l'eau" },
    { english: "They are having dinner", french: "Ils dînent" },
    { english: "I like to read books", french: "J'aime lire des livres" },
    { english: "She is playing tennis", french: "Elle joue au tennis" },
    { english: "We are dancing in the party", french: "Nous dansons à la fête" },
    { english: "He is driving a car", french: "Il conduit une voiture" },
    { english: "They are sleeping", french: "Ils dorment" },
    { english: "I am watching a movie", french: "Je regarde un film" },
    { english: "She is riding a bike", french: "Elle fait du vélo" },
    { english: "We are studying French", french: "Nous étudions le français" },
    { english: "He is talking on the phone", french: "Il parle au téléphone" },
    { english: "They are playing video games", french: "Ils jouent aux jeux vidéo" },
    { english: "I like to eat pizza", french: "J'aime manger de la pizza" },
    { english: "She is singing a song", french: "Elle chante une chanson" },
    { english: "He is working in the garden", french: "Il travaille dans le jardin" },
    { english: "They are swimming in the pool", french: "Ils nagent dans la piscine" },
    { english: "I am writing a letter", french: "J'écris une lettre" },
    { english: "She is shopping in the mall", french: "Elle fait du shopping dans le centre commercial" },
    { english: "We are cooking breakfast", french: "Nous préparons le petit-déjeuner" },
    { english: "He is playing with his dog", french: "Il joue avec son chien" },
    { english: "They are waiting for the bus", french: "Ils attendent le bus" },
    { english: "I like to watch movies", french: "J'aime regarder des films" },
    { english: "She is studying at the library", french: "Elle étudie à la bibliothèque" },
    { english: "We are having lunch at a restaurant", french: "Nous déjeunons au restaurant" },
    { english: "He is playing the guitar", french: "Il joue de la guitare" },
    { english: "They are walking in the city", french: "Ils se promènent dans la ville" },
    { english: "I am reading a novel", french: "Je lis un roman" },
    { english: "She is taking a nap", french: "Elle fait une sieste" },
    { english: "We are watching a football match", french: "Nous regardons un match de football" },
    { english: "He is doing homework", french: "Il fait ses devoirs" },
    { english: "They are having a picnic", french: "Ils font un pique-nique" },
    { english: "I like to drink tea", french: "J'aime boire du thé" },
    { english: "She is playing chess with her brother", french: "Elle joue aux échecs avec son frère" },
    { english: "We are traveling to Europe", french: "Nous voyageons en Europe" },
    { english: "He is painting a landscape", french: "Il peint un paysage" },
    { english: "They are having breakfast together", french: "Ils prennent le petit-déjeuner ensemble" },
    { english: "I am running in the park", french: "Je cours dans le parc" },
    { english: "She is studying for her exams", french: "Elle étudie pour ses examens" },
    { english: "We are going on a road trip", french: "Nous partons en voyage sur la route" },
    { english: "He is playing basketball with his friends", french: "Il joue au basket avec ses amis" },
    { english: "They are having a barbecue party", french: "Ils font une fête barbecue" },
    { english: "I like to go hiking in the mountains", french: "J'aime faire de la randonnée en montagne" },
    { english: "She is taking photographs", french: "Elle prend des photos" },
    { english: "We are going to the cinema tonight", french: "Nous allons au cinéma ce soir" },
    { english: "He is doing yoga in the park", french: "Il fait du yoga dans le parc" },
    { english: "They are having a sleepover", french: "Ils font une soirée pyjama" },
    { english: "I am baking cookies", french: "Je fais des cookies" },
    { english: "She is playing with her cat", french: "Elle joue avec son chat" },
    { english: "We are having a family reunion", french: "Nous avons une réunion de famille" },
    { english: "He is riding a horse", french: "Il fait du cheval" },
    { english: "They are going to a music concert", french: "Ils vont à un concert de musique" },
    { english: "I like to go fishing", french: "J'aime aller pêcher" },
    { english: "She is learning to dance salsa", french: "Elle apprend à danser la salsa" },
    { english: "We are going to the beach for vacation", french: "Nous partons à la plage en vacances" },
    { english: "He is studying computer science", french: "Il étudie l'informatique" },
    { english: "They are playing board games", french: "Ils jouent à des jeux de société" },
    { english: "I am writing poetry", french: "J'écris de la poésie" },
    { english: "She is jogging in the park", french: "Elle fait du jogging dans le parc" },
    { english: "We are having a potluck dinner", french: "Nous organisons un dîner partage" },
    { english: "He is taking a language course", french: "Il suit un cours de langue" },
    { english: "They are having a movie marathon", french: "Ils font un marathon de films" },
    { english: "I like to go camping in the wilderness", french: "J'aime aller camper dans la nature sauvage" },
    { english: "She is knitting a sweater", french: "Elle tricote un pull" },
    { english: "We are going to visit historical landmarks", french: "Nous allons visiter des sites historiques" },
    { english: "He is volunteering at a local charity", french: "Il fait du bénévolat dans une association locale" },
    { english: "They are playing in a band", french: "Ils jouent dans un groupe de musique" },
];